# Generated by Django 4.1.4 on 2022-12-14 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('envs', models.JSONField()),
                ('command', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('finished', 'Finished')], max_length=10)),
                ('running_time', models.DurationField()),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('envs', models.JSONField()),
                ('command', models.CharField(max_length=100)),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.app')),
            ],
        ),
    ]
