# Generated by Django 4.1.4 on 2022-12-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_run_img_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='running_time',
            field=models.FloatField(default=0),
        ),
    ]
