# Generated by Django 4.1.4 on 2022-12-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_run_running_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='envs',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='running_time',
            field=models.IntegerField(default=0),
        ),
    ]
