# Generated by Django 4.1.4 on 2022-12-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_app_envs_alter_run_running_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='command',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
