# Generated by Django 4.1.4 on 2022-12-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_app_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='command',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='envs',
            field=models.JSONField(null=True),
        ),
    ]
