# Generated by Django 4.1.4 on 2022-12-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_run_command_alter_run_envs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='img_id',
        ),
        migrations.AddField(
            model_name='run',
            name='cont_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
