# Generated by Django 4.1.4 on 2022-12-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_run_cont_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='cont_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
